### PR TITLE
Remove unused errors

### LINKED ISSUE #37: Code smell: error is never produced in Shutdown
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Both the `Health` and `Latency` `Checks` never return an error when running the `Shutdown` implementation. We should either: 

- check for error cases and return them (catch eventual panics that could happen in the channels (`h.done <- true`, done has a capacity of 1)
- remove the error from the function alltogether

### Expected Behavior

Functions that return errors, which are ignored or only logged are a code smell. An error means that something has gone wrong and should be handled.

### Steps To Reproduce

No reproduction needed.

### Relevant logs and/or screenshots, environment information, etc.

_No response_

### Who can address the issue?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by puffitos**
## Motivation

Closes #37 - no need to carry corpses around in the codebase.

## Changes

See commits. Removed unused err values and ctx values as well from all shutdown functions of the checks, and updated the checkController's shutdown as well (it was never returing an err).

## Tests done

- [x] Unit tests succeeded
- [ ] E2E tests succeeded - not running any as we have none

## TODO

- [x] I've assigned this PR to myself
- [x] I've labeled this PR correctly

### CODE REVIEW

File: pkg/sparrow/controller.go [hunk 1]
```diff
@@ -125,7 +119,7 @@ func (cc *ChecksController) Reconcile(ctx context.Context, cfg runtime.Config) {
 
 	// Unregister checks not in the new config
 	for _, c := range unregList {
-		err = cc.UnregisterCheck(ctx, c)
+		cc.UnregisterCheck(ctx, c)
 		if err != nil {
 			log.ErrorContext(ctx, "Failed to unregister check", "check", c.Name(), "error", err)
 		}
```
Comment (lvlcn-t) [inline pkg/sparrow/controller.go:125]: This can also be removed

**Review by lvlcn-t — COMMENTED** [review]
One minor thing, otherwise LGTM

File: pkg/sparrow/controller.go (hunk 1 above)
Comment (puffitos) [reply pkg/sparrow/controller.go]: Removed it, thanks for the review. The `RegistrerCheck` also never seems to return an error, it just pumps everything down the error channel... I'll change that in a later PR.

File: pkg/sparrow/controller.go [hunk 2]
```diff
@@ -83,13 +80,10 @@ func (cc *ChecksController) Run(ctx context.Context) error {
 // Shutdown shuts down the ChecksController.
 func (cc *ChecksController) Shutdown(ctx context.Context) (err error) {
```
Comment (lvlcn-t) [inline pkg/sparrow/controller.go:81]: You may also remove the error return here, either in this PR or in the later one for #123

File: pkg/sparrow/controller_test.go [hunk 3]
```diff
@@ -302,45 +300,13 @@ func TestChecksController_UnregisterCheck(t *testing.T) {
 			check:   health.NewCheck(),
 			wantErr: false,
```
Comment (lvlcn-t) [inline pkg/sparrow/controller_test.go:301]: This field can be removed now

File: pkg/sparrow/controller.go (hunk 2 above)
Comment (puffitos) [reply pkg/sparrow/controller.go:81]: Later

File: pkg/sparrow/controller_test.go (hunk 3 above)
Comment (puffitos) [reply pkg/sparrow/controller_test.go:301]: I'll do this in the #123, as the tests need to be refactored to truly test some use cases.

**Review by lvlcn-t — APPROVED** [review]
